services:
  - type: web
    name: symfony-app
    env: php
    buildCommand: composer install && npm install && npm run build
    startCommand: heroku-php-apache2 public/
    staticPublishPath: public/build
    envVars:
      - key: APP_ENV
        value: test
        previewValue: test
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: mysql://test_user:test_password123@mysql_dev:3306/stage_test
        previewValue: mysql://test_user:test_password123@mysql_dev:3306/stage_test
        fromDatabase:
          name: symfony_db
          property: connectionString
    healthCheckPath: /health

  - type: redis
    name: symfony-redis
    ipAllowList: []
    plan: free

databases:
  - name: symfony_db
    databaseName: stage
    user: test_user
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
staticSites:
  - name: symfony-assets
    buildCommand: npm run build
    publishPath: public/build
    pullRequestPreviewsEnabled: false
